FROM docker.n8n.io/n8nio/n8n:latest

USER root

RUN apk add --no-cache \
    python3 \
    py3-pip \
    bash

RUN pip3 install --break-system-packages \
    psycopg2-binary \
    requests \
    python-dotenv

USER node